sudo: false
language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "nightly" # currently points to 3.6-dev

addons:
  apt:
    sources:
    - debian-sid
    packages:
    - liblz4-tool

# dependencies from requirements.txt are automatically installed

# command to run tests
script: python -m pytest
